### ISSUE TITLE
Unable to get new versions

### ISSUE THREAD

**Issue by Kralizek** [JetBrains/aspire-plugin#282]
Are new releases expected to appear in the Rider plugin menu? My Rider is stuck on 1.4 and doesn't get the new updates.

**Comment by rafaelldi** [comment]
Unfortunately, the only way to update is to do it manually. I can't do anything on the plugin side. This should be fixed in the next 2025.1 release when the plugin is properly bundled with Rider.

<img width="741" alt="image" src="https://github.com/user-attachments/assets/814f341f-df37-41e1-b5b3-da38f65e9328">
